version: '3.8'

services:
  chatapp:
    build: .
    container_name: chatapp
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-default-secret-key-change-in-production}
      - FLASK_ENV=production
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-change_me_please!}
      - ENABLE_AUTH=${ENABLE_AUTH:-true}
      - ENABLE_MULTI_USER=${ENABLE_MULTI_USER:-true}
      - USERS_CONFIG=${USERS_CONFIG:-}
    volumes:
      - ./static/uploads:/app/static/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - chatapp-network

networks:
  chatapp-network:
    driver: bridge
